### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by benlevi1** [apoelstra/rust-jsonrpc#106]
Hey folks,

First of all, I would like to thank you for an amazing library.
I am trying to work with a bitcoin instance via HTTPs (it is behind a gateway).
As far as I see, the client does not support the protocol: it does relate to "https" by adding the port `443` but there is no actual TLS handling.
Do you have any plans implementing it or is there any workaround?

**Comment by apoelstra** [comment]
We may add a `minreq` backend which has HTTPS support, and soft-deprecate our hand-rolled HTTP client (which seems to be subtly broken on certain platforms). The timeline for that is months, not weeks. Hopefully not years.  I'm not sure who, if anybody, is actively working on it right now.

But we don't intend to implement HTTPS support ourselves.

**Comment by tcharding** [comment]
Adding HTTPS support by way of `minreq` shouldn't be too hard. I doubt it is that much work, for my part I don't like doing things unless I at least attempt to do them thoroughly and I have not found myself motivated enough by this work to do it thoroughly. I'm more than happy to review it if you feel like adding it @benlevi1, would be a useful addition to the crate IMO.

**Comment by tcharding** [comment]
`minreq` is implemented now and it provides HTTPS, this can be closed.
