### ISSUE TITLE
jsonrpc field missing from request

### ISSUE THREAD

**Issue by ecksun** [apoelstra/rust-jsonrpc#2]
I'm doing my first project in rust and when trying to use this library I noticed that the jsonrpc field is missing from the request, using wireshark:

```
POST /jsonrpc HTTP/1.1
Host: some.host
Content-Length: 55

{"method":"Player.GetActivePlayers","params":[],"id":1}
```

A proper jsonrpc 2.0 message MUST include the jsonrpc field (and have a value of `"2.0"`) according to http://www.jsonrpc.org/specification

That is, the proper request should be:

    {"jsonrpc":"2.0","method":"Player.GetActivePlayers","params":[],"id":1}

I haven't figured out enough of rust/cargo to submit a patch yet though.

**Comment by apoelstra** [comment]
Fixed by https://github.com/apoelstra/rust-jsonrpc/issues/3

**Comment by ecksun** [comment]
Alright, I just realized fixing the response. I have been up and down serde trying to figure out why it couldn't parse the response, and its obviously because the Response object doesn't have the jsonrpc field either.

I will hopefully soon submit a patch which addresses that as well.
