### ISSUE TITLE
Connection reset by peer is not handled properly

### ISSUE THREAD

**Issue by calvinaco** [apoelstra/rust-jsonrpc#26]
### Problem:
When the underlying Hyper client connection is reset, the first JSON-RPC request call will fail with
```
Err(Hyper(Io(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })))
```

Afterwards, the second call will work again.

### What I think should be the expected behaviour?
I expect a new client should be created whenever the underlying connection is reset. And the `send_request()` call should seamlessly switch to use the new connection as if nothing has happened underneath.

**Comment by apoelstra** [comment]
We already have logic for this; see https://github.com/apoelstra/rust-jsonrpc/commit/394729f73ff0c15d11949efb671b5e25de82918d where it broke in a minor version of hyper.

**Comment by apoelstra** [comment]
Are you saying there's another kind of error return that we should detect and retry?

**Comment by calvinaco** [comment]
Yes I think `ConnectionReset` should be detected and retry in library level. Because when socket is closed on remote most of the time all it need is reconnect.

But right now it shifted the responsibility of retry on `ConnectionReset` to project integrating the library.

**Comment by tcharding** [comment]
We don't use `hyper` anymore, I think this issue can be closed.
