### ISSUE TITLE
Ethereum jsonrpc support

### ISSUE THREAD

**Issue by AchalaSB** [apoelstra/rust-jsonrpc#27]
Hi,
I'm trying to connect rust code to ethereum ? Is there any luck using this jsonrpc?? and it should compatible with webassembly as well.

Or any other crates we have?

Thanks

**Comment by apoelstra** [comment]
It would surprise me if this crate were compatible with geth or Parity, sorry. This isn't an intended or supported usecase, and none of the developers have the spare time or equipment to maintain Ethereum nodes for testing.

**Comment by dpc** [comment]
> It would surprise me if this crate were compatible with geth or Parity, sorry. 

I think `rust-jsonrpc` is quite plain standard JsonRPC, no? So as long as Parity conforms the jsonrpc layer should work just fine.

@AchalaSB Now, it's a different matter entirely to write and maintain a crate for higher-level operations (akin to `rust-bitcoincore-rpc`).

> and it should compatible with webassembly as well.

I don't know what webassembly has to do with anything. `rust-jsonrpc` is only for https://www.jsonrpc.org/specification protocol.

**Comment by tcharding** [comment]
Hi @AchalaSB can this issue be closed now?
