### ISSUE TITLE
Add support for batched RPC requests in client

### ISSUE THREAD

**Issue by devashishdxt** [apoelstra/rust-jsonrpc#28]
https://www.jsonrpc.org/specification#batch

**Comment by dpc** [comment]
Implemented already in https://github.com/apoelstra/rust-jsonrpc/commit/eec5ec8516021a79a0a0f8a65ca38be5b85c5c4b

**Comment by devashishdxt** [comment]
Any plan for releasing a new version?

**Comment by devashishdxt** [comment]
Closing this issue
