### ISSUE TITLE
`Client::simple_http` should take `impl Into<String>`

### ISSUE THREAD

**Issue by Kixunil** [apoelstra/rust-jsonrpc#55]
Because this method takes `&str` it forces `bitcoincore-rpc` to require `&str` which is wasteful if one constructs the url using `format!()` - causes one more allocation.

**Comment by tcharding** [comment]
I took a look at this but cannot work it out, the call chain is:
`bitcoincore_rpc::Client::new()` -> `jsonrpc::client::Client::simple_http()` -> `Builder::new().url()` -> `check_url()` which does a bunch of stuff with references into the `& str: url` argument that has been passed down the callchain. We never consume the argument. 

1. Why would we want to call `into` to get a `String`? 
2. How does the code cause one more allocation?

Or is this issue stale?

**Comment by Kixunil** [comment]
Good point, looks like I got confused.
