### ISSUE TITLE
[Feature Request] Enable Socks5 proxy support at Transport level

### ISSUE THREAD

**Issue by rajarshimaitra** [apoelstra/rust-jsonrpc#57]
We had an usecase in BDK to have core-rpc client talk through a Tor proxy, like the electrum client, via a proxy configuration.

Potential use case: Mobile devices trying to connect to an Umbrel running at home for personal wallet usage via Tor.

Intention is to get RPC calls through Tor via cookie authentication through a Socks5 transport.

When I tried implementing it I ended up recreating the same `SimpleHttpTransport` for Socks5 in this PR in BDK
https://github.com/bitcoindevkit/bdk/pull/493

The resting `Transport` looks like this.  
https://github.com/bitcoindevkit/bdk/blob/b99f1cf6309c3daa6b7d432ecd77bbc69862af44/src/blockchain/rpc_proxy.rs

But its essentially duplicating code from low level, for an high level application.

Opening this issue to start discussing on the best approach to integrate it in `jsonrpc` level and then in `bitcoincore-rpc`.

My suggestion would be to add another module name `simple_socks5` and export that back to `bitcoincore-rpc`. Use that specific transport, if proxy options are set in client config. (Also maybe via a feature flag?)

I am open to work on the PR for this crate and for `bitcoincore-rpc`, if we can decide on the approach.

**Comment by apoelstra** [comment]
This seems like a good idea. I notice that your `socks` dependency looks pretty solid: it has only a couple dependencies, all of which are long-stable and well maintained. One is `byteorder` which broke our MSRV unexpectedly in the past, but this is not a hill worth dying on.

I think the first step would be to update the MSRV of **this** library from 1.29 and 1.41, modernize the code a bit.

@tcharding are you willing to take a look at this? I think we're close to being able to pull this project under the rust-bitcoin org, it just needs a little bit of love.

**Comment by rajarshimaitra** [comment]
Thanks @apoelstra for the look.. I believe it can be a really useful feature not just for BDK but for core rpc in general too.. There is really no good way to use home nodes under dynamic IPs for personal usages without Tor.

Wallet devs mostly need to cook up their own solutions today.. But having native support in bitcoincore-rpc will be very helpful for downstream usage..

**Comment by tcharding** [comment]
> @tcharding are you willing to take a look at this?

Sure thing, no sweat.

**Comment by tcharding** [comment]
Done: https://github.com/apoelstra/rust-jsonrpc/pull/58

A lot of patches but should all be pretty easy to review.

**Comment by rajarshimaitra** [comment]
Sorry took me some time to get back to this.. Is it PR-able now?? I can work on getting a proxy inside the Transport.. Open to suggestion on easiest approach.. 

I think some way of making the `SimpleHttpTransport` take up a Socks5 socket via a config flag, or feature gate would be least amount of code?

**Comment by apoelstra** [comment]
Yeah, that'd be awesome.

**Comment by apoelstra** [comment]
Fixed in #70
