### ISSUE TITLE
Update for serde 0.7

### ISSUE THREAD

**Issue by alexreg** [apoelstra/rust-jsonrpc#6]

**Comment by alexreg** [comment]
It would be great to have one.

Is there any reason you're using caret dependencies, by the way?

**Comment by alexreg** [comment]
I was also thinking of porting to use `serde_json` instead of `strason` (which has that one really nasty hack, even though I like the aim of the project)...

**Comment by apoelstra** [comment]
@alexreg using `serde_json` would make this completely useless for its main goal, which is communicating with Bitcoin Core.

**Comment by apoelstra** [comment]
Note the original reason I created `strason`:
https://github.com/serde-rs/json/issues/18
https://github.com/serde-rs/serde/issues/185

We're at 9 months now, with no progress in the main serde library except to break my hack in 0.7.

**Comment by alexreg** [comment]
Yeah, so it's all about bignum/decimal support, basically. I was hoping *serde_json* could just deserialize numbers as strings too... I guess not?

Let's re-evaluate when that feature is integrated, in any case.

**Comment by apoelstra** [comment]
Yep, you've got it.

Certainly we'll reevaluate. I'd love to retire strason.
