### ISSUE TITLE
Move from hyper to reqwest.

### ISSUE THREAD

**Issue by jeandudey** [apoelstra/rust-jsonrpc#9]
Hyper is now a low-level http library focusing more on asynchronous I/O, updating it doesn't make sense because rust-jsonrpc provides an synchronous API that's more simpler and fits with older hyper versions. Now I propose to move form hyper to reqwest which provides a synchronous API and is similar to older hyper version plus bug-fixes and improvements.

This can be done right now because reqwest includes support for TLS by default and thus including a lot of unneeded libraries for cases where TLS isn't needed (see #7 discussion about this). This upgrade should be done when reqwest adds support for a cargo feature to disable TLS (see seanmonstar/reqwest#225 for the tracking issue).

**Comment by apoelstra** [comment]
Leaving this open. Unfortunately I think the resolution will be to create our own HTTP library which really does something simple and synchronous. reqwest currently has 84 dependencies, including the TLS stuff, which is unmanageable for security-aware applications.

**Comment by stevenroose** [comment]
Solved by #20.

**Comment by dpc** [comment]
I asked around for a best small-crate to do http with: https://users.rust-lang.org/t/lightweight-alternative-for-reqwest/33601/19

So far [attohttpc](https://github.com/sbstp/attohttpc) seems to be the  [most suitable](https://github.com/dpc/crev-proofs/commit/77cf6ac1f401c5c8e84adbdb50df24826e5a7c16)

**Comment by tcharding** [comment]
I think this can be closed now.
